# Generated by Django 4.1.6 on 2023-02-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=2, verbose_name='Серия карты')),
                ('number', models.IntegerField(verbose_name='Номер карты')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время выпуска карты')),
                ('start_activate_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время активации карты')),
                ('date_of_last_use', models.DateTimeField(auto_now=True, verbose_name='Дата и время последнего использования')),
                ('finish_date', models.DateTimeField(verbose_name='Дата и время окончания активности карты')),
                ('orders_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Сумма покупок')),
                ('card_status', models.CharField(choices=[('Не активирована', 'Не активирована'), ('Активирована', 'Активирована'), ('Просрочена', 'Просрочена')], default='Не активирована', max_length=16, verbose_name='Статус карты')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Текущая скидка (%)')),
                ('trash', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_purchase', models.DateTimeField(auto_now=True, verbose_name='Дата и время покупки')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма заказа')),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Скидка (%)')),
                ('total_amount_with_discount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма заказа с учётом скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма скидки')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('price_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена со скидкой')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество штук')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Итого')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.product')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
